
@URL = http://localhost:3000
@roomID = 
@messageID = 

### POST Create room 
POST {{URL}}/rooms/
Content-Type: application/json
x-user-id: random-uuid

{
  "name": "sala3"
}


### POST Add user/member
POST {{URL}}/rooms/{{roomID}}/members
Content-Type: application/json
x-user-id: random-uuid

{
  "user_id": "random-uuid"
}


### POST Send message
POST {{URL}}/rooms/{{roomID}}/messages
Content-Type: application/json
x-user-id: random-uuid

{
  "message": "Hello world! Happy to be here"
}

### GET messages
GET {{URL}}/rooms/{{roomID}}/messages
Content-Type: application/json
x-user-id: random-uuid

### DELETE Remove message
DELETE {{URL}}/rooms/messages/{{messageID}}
Content-Type: application/json
x-user-id: random-uuid
