
@URL = http://localhost:3000
@roomID = b6d6e869-f050-427b-a463-2f4680cdf379
@messageID = f518ff7f-a11b-46f0-b7af-3f57f20d1d8f

### POST Create room 
POST {{URL}}/rooms/
Content-Type: application/json
x-user-id: random-uuid

{
  "name": "sala3"
}


### POST Add user/member
POST {{URL}}/rooms/{{roomID}}/member
Content-Type: application/json
x-user-id: random-uuid

{
  "user_id": "random-uuid"
}


### POST Send message
POST {{URL}}/rooms/{{roomID}}/message
Content-Type: application/json
x-user-id: random-uuid

{
  "message": "Hello world! Happy to be here"
}

### DELETE Remove message
DELETE {{URL}}/rooms/messages/{{messageID}}
Content-Type: application/json
x-user-id: random-uuid
